// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxiOdPnfswB2CWO4si7F-AWT0KAiUGfJs',
    appId: '1:183371451794:web:82f6d32e040258a88bc54b',
    messagingSenderId: '183371451794',
    projectId: 'flutter-cafri-crud-test',
    authDomain: 'flutter-cafri-crud-test.firebaseapp.com',
    storageBucket: 'flutter-cafri-crud-test.firebasestorage.app',
    measurementId: 'G-L10RS1QEKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZcXXlBDbjbXQ-eYxK_sQKRwoNydSxspA',
    appId: '1:183371451794:android:9c7dedcbcbdf1ef38bc54b',
    messagingSenderId: '183371451794',
    projectId: 'flutter-cafri-crud-test',
    storageBucket: 'flutter-cafri-crud-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQfytKz2WcvTUAUxjpr6xTxcek7axJbo',
    appId: '1:183371451794:ios:13dcc3711e7ebfc08bc54b',
    messagingSenderId: '183371451794',
    projectId: 'flutter-cafri-crud-test',
    storageBucket: 'flutter-cafri-crud-test.firebasestorage.app',
    iosBundleId: 'com.example.cafri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQfytKz2WcvTUAUxjpr6xTxcek7axJbo',
    appId: '1:183371451794:ios:13dcc3711e7ebfc08bc54b',
    messagingSenderId: '183371451794',
    projectId: 'flutter-cafri-crud-test',
    storageBucket: 'flutter-cafri-crud-test.firebasestorage.app',
    iosBundleId: 'com.example.cafri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxiOdPnfswB2CWO4si7F-AWT0KAiUGfJs',
    appId: '1:183371451794:web:3aebadf54ab7c30f8bc54b',
    messagingSenderId: '183371451794',
    projectId: 'flutter-cafri-crud-test',
    authDomain: 'flutter-cafri-crud-test.firebaseapp.com',
    storageBucket: 'flutter-cafri-crud-test.firebasestorage.app',
    measurementId: 'G-T3VLG14BH5',
  );
}
